name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  graphql_flutter: ^5.1.2
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.8.0
  skeletonizer: ^1.4.2
  just_audio: ^0.9.42
  animate_do: ^3.3.4
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  http: ^1.2.2
  share_plus: ^10.1.2
  screenshot: ^3.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
